apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: croyce97/backend-pern:v1
        ports:
        - containerPort: 3001
        env:
        - name: DATABASE_URL
          value: "postgres://postgres:postgres@postgres:5432/yelp"
        - name: PORT
          value: "3001"


---

apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
  type: ClusterIP
  

